### ISSUE TITLE
Repository still available to the public

### ISSUE THREAD

**Issue by avocadosec** [rackerlabs/castle-map#4]
Just wanted to note that you can still access this repository as a non-rackerlabs user. Not sure if needed but I would recommend deleting or transferring the repo to a private repo.

**Comment by runrog** [comment]
Thanks, wanted to leave this up for a couple of days before I shut it off as it's hosting the redirect page. It'll be moved to an internal repo -> https://github.rackspace.com/roge5716/castle-map
